services:
  ydb:
    image: ydbplatform/local-ydb:25.1.4
    platform: linux/amd64
    ports:
      - 2135:2135
      - 2136:2136
      - 8765:8765
      - 9092:9092
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_KAFKA_PROXY_PORT: 9092
    volumes:
      - ./ydb_certs:/ydb_certs
      - ydb_data:/ydb_data
  pg:
    image: postgres:15-alpine
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pg_data:/var/lib/postgresql/data
volumes:
  ydb_data:
